- name: Install gdown with pip
  pip: name=gdown

- name: Install docker
  yum: name=docker

- name: Ensure service is enabled
  command: service docker restart

- name: Creates working directory
  file:
    path: "{{ work_dir }}"
    state: directory

- name: Download folder with data
  command: "{{ item }}"
  with_items:
    - gdown https://drive.google.com/uc?id=1SFL-gYzu9RIIDFY4uBt-_TamHHmfROVG
    - tar -xzvf folder_test.tar.gz
    - rm folder_test.tar.gz
  args:
    chdir: "{{ work_dir }}"

- name: Pull default Docker image
  docker_image:
    name: "{{ default_container_image }}"
    #  pull: yes

- name: Create default containers
  docker_container:
    detach: false
    name: "{{ default_container_name }}"
    image: "{{ default_container_image }}"
    command: "{{ default_container_command }}"
    volumes:
      - "{{ work_dir }}/folder_test:/data/folder_test"
    state: started
  when: run=="true"
